[phases.setup]
nixPkgs = ['docker']

[phases.install]
cmd = ''

[phases.build]
cmds = ['docker compose -f docker/docker-compose.dev.yaml build']

[start]
cmd = 'docker compose -f docker/docker-compose.dev.yaml up'
